
start: sourse.o avl_var_tree.o api.o calculate.o
	gcc -o start sourse.o avl_var_tree.o api.o calculate.o

sourse.o: sourse.c
	gcc -c  sourse.c

avl_var_tree.o: avl_var_tree.c
	gcc -c avl_var_tree.c

api.o: api.c
	gcc -c  api.c

calculate.o: calculate.c
	gcc -c  calculate.c

clean:
	rm -rf *.o	



